fixes for GAMESS-US easyblock (WIP)
easybuilders/easybuild-easyblocks pull request #1925
Opened 2020-01-14 20:18 UTC by boegel

(not finished, but it's getting on my nerves having this in my working copy)

cc @guacke

2020-02-17 09:57 UTC, branfosj commented
I've been looking at GAMESS-US for one of our users. I've not successfully completed it yet, but noticed that `maxcpus` and `maxnodes` are defined as variables in the EasyBlock and defined in the EasyConfigs. However, they do not seem to ever be used. I've added the following to the WIP I have for the EasyBlock:
```
        compddi = os.path.join(self.builddir, 'ddi/compddi')
        try:
            for line in fileinput.input(compddi, inplace=1, backup='.orig'):
                line = re.sub(r"^\s*set\s*MAXCPUS=.*", r"set MAXCPUS=%s" % self.cfg['maxcpus'], line)
                line = re.sub(r"^\s*set\s*MAXNODES=.*", r"set MAXNODES=%s" % self.cfg['maxnodes'], line)
                sys.stdout.write(line)
        except IOError as err:
            raise EasyBuildError("Failed to patch %s: %s", compddi, err)
```

2020-09-27 06:49 UTC, akesandgren requested changes

2020-09-27 06:49 UTC, akesandgren commented on easybuild/easyblocks/g/gamess_us.py
> +                raise EasyBuildError("Temporary dir for tests '%s' will cause problems with rungms csh script",
Should probably tell the user why it will cause problems.

2020-09-27 06:49 UTC, akesandgren commented on easybuild/easyblocks/g/gamess_us.py
> +            test_cmd = 'ssh localhost "ls %s"' % test_file
This is not a good thing to do. Think building in a container...
If rungms tries to do any ssh-based stuff it is broken and should be fixed.
I don't think I had that problem back in the days I built this by hand.

2023-12-14 11:52 UTC, lexming commented
Closing as superseded by https://github.com/easybuilders/easybuild-easyblocks/pull/3047

2023-12-14 11:52 UTC, closed without merging