also consider libfabric dep (--with-ofi) when setting default OpenMPI configure options
easybuilders/easybuild-easyblocks pull request #2184
Opened 2020-09-22 17:25 UTC by boegel

(created using `eb --new-pr`)

2020-09-22 17:48 UTC, Micket approved these changes
lgtm

2020-09-22 18:39 UTC, Micket requested changes

2020-09-22 18:39 UTC, Micket commented on easybuild/easyblocks/o/openmpi.py
> +                    if dep in 'libfabric':
```suggestion
                    if dep == 'libfabric':
```

2020-09-23 08:26 UTC, boegel commented on easybuild/easyblocks/o/openmpi.py
> +                    if dep in 'libfabric':
Oh nice catch 🤦

2020-09-23 08:29 UTC, Micket approved these changes
lgtm

2020-09-23 08:43 UTC, merged