Update Clang easyblock
easybuilders/easybuild-easyblocks pull request #2310
Opened 2021-01-15 15:38 UTC by geimer

Add support for building the extra Clang tools, and optionally configuring use of `hwloc` by the OpenMP runtime, and `Z3` bei the Clang static analyzer.

2021-01-15 16:43 UTC, ocaisa approved these changes
LGTM, might be a while before generoso can build and test this on the open easyconfig PR

2021-01-15 16:53 UTC, ocaisa requested changes
Minor comment

2021-01-15 16:53 UTC, ocaisa commented on easybuild/easyblocks/c/clang.py
> +            find_source_dir('clang-tools-extra-*', os.path.join(self.llvm_src_dir, 'tools/clang/tools', 'extra'))
Please use
```
find_source_dir('clang-tools-extra-*', os.path.join(self.llvm_src_dir, 'tools, 'clang', 'tools', 'extra'))
```

2021-01-16 09:06 UTC, boegel commented on easybuild/easyblocks/c/clang.py
> +            find_source_dir('clang-tools-extra-*', os.path.join(self.llvm_src_dir, 'tools/clang/tools', 'extra'))
fixed in 95a5e0887

2021-01-16 12:17 UTC, boegel approved these changes
lgtm

2021-01-16 13:13 UTC, boegel commented
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Clang-6.0.1-GCC-6.4.0-2.28.eb_ 
 * **SUCCESS** _Clang-9.0.1-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _Clang-11.0.0-GCCcore-9.3.0.eb_ 

Build succeeded for 3 out of 3 (3 easyconfigs in total)
node2606.swalot.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz (haswell), Python 3.6.8
See https://gist.github.com/d6647eac4099662c5fe21d21288b2ded for a full test report.

2021-01-16 13:16 UTC, merged

2021-01-16 13:17 UTC, boegel commented
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Clang-6.0.1-GCC-6.4.0-2.28.eb_ 
 * **SUCCESS** _Clang-8.0.0-GCCcore-8.2.0.eb_ 
 * **SUCCESS** _Clang-10.0.0-GCCcore-9.3.0.eb_ 

Build succeeded for 3 out of 3 (3 easyconfigs in total)
node3136.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, Python 3.6.8
See https://gist.github.com/daf600641cb99b7c905a7d355ed0615a for a full test report.