Fix OpenFOAM sanity check on POWER
easybuilders/easybuild-easyblocks pull request #2320
Opened 2021-01-26 16:09 UTC by branfosj

(created using `eb --new-pr`)

2021-01-26 20:18 UTC, branfosj commented
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenFOAM-8-foss-2020a.eb_ 
 * **SUCCESS** _CGAL-4.14.1-foss-2019b-Python-3.7.4.eb_ 
 * **SUCCESS** _libcerf-1.13-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _Lua-5.1.5-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _gnuplot-5.2.8-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _OpenFOAM-v1912-foss-2019b.eb_ 

Build succeeded for 6 out of 6 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/5a077031b5b7dc580318f64f3077d9fb for a full test report.

2021-01-26 23:59 UTC, branfosj commented
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenFOAM-6-foss-2019b.eb_ 
 * **SUCCESS** _OpenFOAM-7-foss-2019b.eb_ 
 * **SUCCESS** _OpenFOAM-7-foss-2019b-20200508.eb_ 
 * **SUCCESS** _OpenFOAM-v1906-foss-2019b.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/43c013f09fde577e9d5d801d0035cd26 for a full test report.

2021-01-27 00:25 UTC, branfosj commented
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenFOAM-v2006-foss-2020a.eb_ 
 * **SUCCESS** _OpenFOAM-8-foss-2020a.eb_ 
 * **SUCCESS** _DBus-1.13.12-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _libevent-2.1.11-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _libcerf-1.13-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _GObject-Introspection-1.63.1-GCCcore-8.3.0-Python-3.7.4.eb_ 
 * **SUCCESS** _JasPer-2.0.14-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _Lua-5.1.5-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _HarfBuzz-2.6.4-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _NSPR-4.21-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _Pango-1.44.7-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _NSS-3.45-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _Qt5-5.13.1-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _gnuplot-5.2.8-GCCcore-8.3.0.eb_ 
 * **FAIL (build issue)** _CGAL-4.14.1-foss-2019b-Python-3.7.4.eb_ (partial log available at https://gist.github.com/eaf3017c867cac16461462712faadd16)
 * **SUCCESS** _ParaView-5.6.2-foss-2019b-Python-3.7.4-mpi.eb_ 
 * **SUCCESS** _OpenFOAM-v1912-foss-2019b.eb_ 

Build succeeded for 16 out of 17 (3 easyconfigs in total)
bear-pg0306u03a.bear.cluster - Linux RHEL 8.2, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/9f305ed554ffac786330d39dd84a3514 for a full test report.

2021-01-27 10:01 UTC, branfosj commented
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenFOAM-v2006-foss-2020a.eb_ 
 * **FAIL (build issue)** _OpenFOAM-v1912-foss-2019b.eb_ (partial log available at https://gist.github.com/1e47b0b9ea52541885001718548a2a00)
 * **FAIL (build issue)** _OpenFOAM-8-foss-2020a.eb_ (partial log available at https://gist.github.com/1d678669dc30829f1b77f819f6f88355)

Build succeeded for 1 out of 3 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/25f31feae976c49fabe5f0146fb262eb for a full test report.

2021-01-27 13:26 UTC, branfosj commented
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenFOAM-v2006-foss-2020a.eb_ 
 * **SUCCESS** _OpenFOAM-v1912-foss-2019b.eb_ 
 * **SUCCESS** _OpenFOAM-8-foss-2020a.eb_ 

Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0306u03a.bear.cluster - Linux RHEL 8.2, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/7129efaa9d454fe58fab9bbb770c0343 for a full test report.

2021-01-27 13:35 UTC, branfosj commented
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenFOAM-6-foss-2019b.eb_ 
 * **SUCCESS** _OpenFOAM-7-foss-2019b-20200508.eb_ 
 * **SUCCESS** _OpenFOAM-7-foss-2019b.eb_ 
 * **SUCCESS** _OpenFOAM-v1906-foss-2019b.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
bear-pg0306u19a - Linux RHEL 8.2, POWER, 8335-GTX (power9le), Python 3.6.8
See https://gist.github.com/d3f927c7e817f2d950a13e902a2298f4 for a full test report.

2021-01-27 13:52 UTC, branfosj commented
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _OpenFOAM-v2006-foss-2020a.eb_ 
 * **SUCCESS** _OpenFOAM-v1912-foss-2019b.eb_ 
 * **SUCCESS** _OpenFOAM-8-foss-2020a.eb_ 

Build succeeded for 3 out of 3 (3 easyconfigs in total)
bear-pg0211u03a.bear.cluster - Linux centos linux 7.8.2003, x86_64, Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz (cascadelake), Python 3.6.8
See https://gist.github.com/c6a6c3bb19b1d1ed550da2443b70f0ce for a full test report.

2021-02-03 14:22 UTC, boegel requested changes
lgtm

2021-02-03 14:22 UTC, boegel approved these changes

2021-02-03 14:22 UTC, merged