Add support for including PTX code in PyTorch
easybuilders/easybuild-easyblocks pull request #2328
Opened 2021-02-02 17:08 UTC by Flamefire

This adds PTX code to PyTorch by default for any newer architecture than the last selected one.
This can be changed by the new EC option "ptx"

2021-02-05 02:25 UTC, Flamefire commented
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _PyTorch-1.7.1-fosscuda-2019b-Python-3.7.4.eb_ (partial log available at https://gist.github.com/3ce737772ff805683c226e500b525c67)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusi8025 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor, Python 2.7.5
See https://gist.github.com/622b16bb5e88fe4a4c51bbb3fd165393 for a full test report.

2021-02-05 08:25 UTC, Flamefire commented
Had to add a bugfix as TORCH_CUDA_ARCH_LIST needs to be set for tests too or the build (even current one) will fail if the GPUs found during build are newer than what the used nvcc supports. See https://gist.github.com/3ce737772ff805683c226e500b525c67

2021-02-06 03:48 UTC, Flamefire commented
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _PyTorch-1.7.1-fosscuda-2019b-Python-3.7.4.eb_ (partial log available at https://gist.github.com/58bf303fda8006243a91887dad037a27)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusi8028 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor, Python 2.7.5
See https://gist.github.com/d30c8f48f9c0948ea0c543797ddff458 for a full test report.

2021-02-06 14:58 UTC, branfosj requested changes

2021-02-08 08:37 UTC, Flamefire commented on easybuild/easyblocks/p/pytorch.py
> +            'ptx': ['latest', 'For which compute architectures PTX code should be generated. Can be '
Good catch! Using "last" which matches "first" and is easiest.

2021-02-08 10:38 UTC, Flamefire commented
I had to add an option for setting up the cuda cache as using `ptx` (by default on) will now possibly trigger JIT compilation which writes to the HOME directory. See https://developer.nvidia.com/blog/cuda-pro-tip-understand-fat-binaries-jit-caching/ for details

There also seems to be a failure which I'm not sure about. Might be because I started the test to early. Will rerun

2021-02-08 12:06 UTC, Flamefire commented
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **FAIL (unhandled exception: must be string, not int)Traceback (most recent call last):
  File "/home/h3/s3248973/.local/EasyBuildDev/easybuild-framework/easybuild/main.py", line 117, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/home/s3248973/.local/EasyBuildDev/easybuild-framework/easybuild/framework/easyblock.py", line 3355, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/home/s3248973/.local/EasyBuildDev/easybuild-framework/easybuild/framework/easyblock.py", line 3254, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/home/s3248973/.local/EasyBuildDev/easybuild-framework/easybuild/framework/easyblock.py", line 3109, in run_step
    step_method(self)()
  File "/tmp/easybuild-tmp/included-easyblocks-22dPoV/easybuild/easyblocks/pytorch.py", line 154, in prepare_step
    env.setvar('CUDA_CACHE_MAXSIZE', cuda_cache_maxsize)
  File "/home/s3248973/.local/EasyBuildDev/easybuild-framework/easybuild/tools/environment.py", line 95, in setvar
    os.environ[key] = value
  File "/usr/lib64/python2.7/os.py", line 471, in __setitem__
    putenv(key, item)
TypeError: must be string, not int
** _PyTorch-1.7.1-fosscuda-2019b-Python-3.7.4.eb_ 

Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusi8030 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor, Python 2.7.5
See https://gist.github.com/d007d98f642101a9ef7751ad533d9cd1 for a full test report.

2021-02-08 22:04 UTC, Flamefire commented
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _PyTorch-1.7.1-fosscuda-2019b-Python-3.7.4.eb_ (partial log available at https://gist.github.com/e727267664fc6530c1bd39b41ea6ae8d)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusi8030 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor, Python 2.7.5
See https://gist.github.com/90415ade2130aaa09b253252f4056979 for a full test report.

2021-02-09 11:29 UTC, Flamefire commented
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _PyTorch-1.7.1-fosscuda-2019b-Python-3.7.4.eb_ (partial log available at https://gist.github.com/44950aa00fa2c6d1f8f31320f07024fe)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusi8029 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor, Python 2.7.5
See https://gist.github.com/dae3bc441be2c9d23ae341a2927a4132 for a full test report.

2021-02-09 11:29 UTC, Flamefire commented
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _PyTorch-1.7.1-fosscuda-2019b-Python-3.7.4.eb_ (partial log available at https://gist.github.com/59482366305af0d8c4c281ca1b85343c)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusml3 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/36f164b76eb48c07eddd9b260cf99d96 for a full test report.

2021-02-09 15:38 UTC, Flamefire commented
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _PyTorch-1.7.1-fosscuda-2019b-Python-3.7.4.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
taurusml3 - Linux RHEL 7.6, POWER, 8335-GTX, Python 2.7.5
See https://gist.github.com/a2fd3c5a7ab9956d83e1df29e62cb6f7 for a full test report.

2021-02-10 12:29 UTC, Flamefire commented
Test report by @Flamefire
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _PyTorch-1.7.1-fosscuda-2019b-Python-3.7.4.eb_ (partial log available at https://gist.github.com/6db857d5e8672a80907e9fd81902f1b0)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
taurusi8033 - Linux centos linux 7.9.2009, x86_64, AMD EPYC 7352 24-Core Processor, Python 2.7.5
See https://gist.github.com/333e42009f7c32b178b429f547deae8b for a full test report.

2021-05-17 07:13 UTC, Flamefire commented
While this does work the amount of JIT compiling that would happen when running the so-compiled PyTorch make this unfeasible. So I'd recommend against using this and am closing it.

2021-05-17 07:13 UTC, closed without merging