disable BioPerl and HTSLib if they are dependencies of VEP
easybuilders/easybuild-easyblocks pull request #2468
Opened 2021-06-11 08:27 UTC by lexming

Currently VEP installs a bundled BioPerl regardless of the dependency in EB

```
 Setting up directories
   - fetching BioPerl
   - unpacking /apps/brussel/CO7/skylake/software/VEP/96.0-foss-2019a-Perl-5.28.1/modules/api/Bio/tmp/release-1-6-924.zip
```

This PR disables the installation of the bundled BioPerl if it is present in the dependency list of VEP.

2021-06-11 16:42 UTC, smoors requested changes
looks good to me, apart from a comment update.
can you also upload a test report?

2021-06-11 16:42 UTC, smoors commented on easybuild/easyblocks/v/vep.py
> +            # disable any bundled dependencies provided by EB
```suggestion
            # disable installation of bundled dependencies that are provided as dependencies in the easyconfig
```

2021-06-11 20:46 UTC, lexming commented
Test report by @lexming
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _VEP-94.0-foss-2018b-Perl-5.28.0.eb_ 
 * **SUCCESS** _VEP-94.5-foss-2017b-Perl-5.26.0.eb_ 
 * **SUCCESS** _VEP-95.0-foss-2018b-Perl-5.28.0.eb_ 
 * **SUCCESS** _VEP-96.0-foss-2019a-Perl-5.28.1.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
node354.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/f07d9529fba7a58c4958661274e45c5b for a full test report.

2021-06-11 21:06 UTC, lexming commented
Test report by @lexming
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _VEP-94.0-foss-2018b-Perl-5.28.0.eb_ 
 * **SUCCESS** _VEP-94.5-foss-2017b-Perl-5.26.0.eb_ 
 * **SUCCESS** _VEP-95.0-foss-2018b-Perl-5.28.0.eb_ 
 * **SUCCESS** _VEP-96.0-foss-2019a-Perl-5.28.1.eb_ 
 * **SUCCESS** _VEP-103.1-GCC-10.2.0.eb_ 

Build succeeded for 5 out of 5 (5 easyconfigs in total)
node354.hydra.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz, Python 2.7.5
See https://gist.github.com/4aad35e9ded85a13bfa4ab3d90dcd3ec for a full test report.

2021-06-11 21:07 UTC, lexming commented
@smoors tasty warm tests out of the oven :slightly_smiling_face:

2021-06-12 09:06 UTC, smoors approved these changes
lgtm

2021-06-12 09:07 UTC, smoors commented
Going in, thanks @lexming!

2021-06-12 09:07 UTC, merged