Enhance intel_compiler easyblock to inlude multipath include dir in $CPATH. See #1237 for original PR.
easybuilders/easybuild-easyblocks pull request #2477
Opened 2021-06-17 08:45 UTC by akesandgren

(created using `eb --new-pr`)

2021-06-17 11:37 UTC, zao commented
Test report by @zao
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _intel-compilers-2021.2.0.eb_ 
 * **SUCCESS** _impi-2021.2.0-intel-compilers-2021.2.0.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
eb-u2004 - Linux Ubuntu 20.04, x86_64, Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, Python 3.8.5
See https://gist.github.com/5607a8bc31bd873a13e2986d9aa5dc4d for a full test report.

2021-06-19 01:31 UTC, bartoldeman requested changes

2021-06-19 01:31 UTC, bartoldeman commented on easybuild/easyblocks/i/intel_compilers.py
> +            multiarch_inc_dir = os.path.join('/usr', 'include', out.strip())
not sure if explicit /usr/include is the best solution here. You can also get this path from:
`gcc -E -Wp,-v -xc /dev/null 2>&1 | grep $(gcc -print-multiarch)$`
it's more complex but avoids the explicit naming.

2021-06-21 11:10 UTC, bartoldeman approved these changes
lgtm

2021-06-21 11:11 UTC, merged