easyblock for crisprdav software
easybuilders/easybuild-easyblocks pull request #2487
Opened 2021-06-23 12:47 UTC by deniskristak

needed to create easyblock due to complex source file changes

2021-06-28 18:57 UTC, boegel requested changes

2021-06-28 18:57 UTC, boegel commented on easybuild/easyblocks/c/crisprdav.py
> +class EB_crisprdav(Binary):
please rename to `EB_CRISP_minus_DAV` (see also https://github.com/easybuilders/easybuild-easyconfigs/pull/13139)

2021-06-28 18:57 UTC, boegel commented on easybuild/easyblocks/c/crisprdav.py
> +CONFIG_FILE_TEXT = """
constants should be defined above the `class` definition

2021-06-28 18:57 UTC, boegel commented on easybuild/easyblocks/c/crisprdav.py
> +abra = {abra2_dir}/abra2-2.23.jar
Wouldn't it be better to copy the `conf.txt`, and do a couple of search-and-replace operations on that?

Shipping a copy of the `conf.txt` in this easyblock makes it a maintenance problem going forward...

2021-06-28 18:57 UTC, boegel commented on easybuild/easyblocks/c/crisprdav.py
> +sample1	{crisprdav_installdir_ex}/rawfastq/sample1_R1.fastq.gz	{crisprdav_installdir_ex}/rawfastq/sample1_R2.fastq.gz
Isn't it better to *generate* this file?

2021-06-28 18:57 UTC, boegel commented on easybuild/easyblocks/c/crisprdav.py
> +        crisprdav_installdir_ex = os.path.join(self.installdir, 'Examples/example1/')
please avoid using `/` in `os.path.join` (same below):

```python
crisprdav_installdir_ex = os.path.join(self.installdir, 'Examples', 'example1')
```

2021-06-28 18:57 UTC, boegel commented on easybuild/easyblocks/c/crisprdav.py
> +        flash_dir = os.environ['EBROOTFLASH']
It's better to use the `get_software_root` function here, and you should also *check* that the result is not `None`, which verifies that these are indeed included as dependencies.

2021-06-28 18:57 UTC, boegel commented on easybuild/easyblocks/c/crisprdav.py
> +EasyBuild support for building and installing Metagenome-Atlas, implemented as an easyblock.
Please fix, this easyblock is for `CRISPR-DAV`, not for `Metagenome-Atlas`

2021-07-05 21:17 UTC, verdurin commented
@deniskristak I tried building the associated easyconfig and saw this error:
```
eb --from-pr=13139 --robot --debug --upload-test-report --include-easyblocks-from-pr 2487
== Temporary log file in case of crash /tmp/eb-jdvm00ah/easybuild-q0xclof4.log
== easyblock crispr_dav.py included from PR #2487
ERROR: Failed to process easyconfig /tmp/eb-jdvm00ah/files_pr13139/c/crispr-dav/crispr-dav-2.3.4-foss-2020b.eb: Failed to obtain class for EB_crisprdav easyblock (not available?): No module named 'easybuild.easyblocks.crisprdav'
```

2021-08-17 11:32 UTC, deniskristak commented
@verdurin correct, i forgot to remove an easyconfig with an the old name. Should be working now

2021-08-18 07:51 UTC, boegel commented
close/re-open to wake up GitHub Actions...

2021-08-19 15:02 UTC, boegel approved these changes

2021-08-19 16:29 UTC, merged