add option to ignore PLUMED version check for GROMACS
easybuilders/easybuild-easyblocks pull request #2621
Opened 2021-11-16 14:34 UTC by smoors

(created using `eb --new-pr`)

2021-11-16 14:44 UTC, akesandgren commented
Yeah, I didn't dare do that by default.

2021-11-24 08:27 UTC, boegel requested changes

2021-11-24 08:27 UTC, boegel commented on easybuild/easyblocks/g/gromacs.py
> +                )
a bit less confusing w.r.t. formatting:

```suggestion
                plumed_ver = get_software_version('PLUMED')
                msg = "There is no support in PLUMED version %s for GROMACS %s: %s" % (plumed_ver, self.version, out)

2021-11-25 22:09 UTC, boegel approved these changes
lgtm

2021-11-25 22:36 UTC, boegel commented
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _GROMACS-2021-foss-2020b.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3152.skitty.os - Linux centos linux 7.9.2009, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/f7185750f503c0af98b44bfcb3aac839 for a full test report.

2021-11-25 22:40 UTC, merged