Change in cudnnarch string templates used to compose source tarball names from cuDNN 8.3.3 onwards
easybuilders/easybuild-easyblocks pull request #2728
Opened 2022-05-31 16:16 UTC by casparvl

Sources are not available from https://developer.download.nvidia.com…/compute/redist/cudnn/ for cudnn 8.3.3 onwards. This might be temporary, but at least blocks adoption of newer cuDNN versions in EasyBuild. This commit implements support for generating source template names for the manually downloaded sources from https://developer.nvidia.com/rdp/cudnn-download for those versions. We could revert this change if the sources are ever still put on .../redist/cudnn/ again in the future.

2022-05-31 16:56 UTC, branfosj commented
See https://github.com/easybuilders/easybuild-easyconfigs/pull/15577#issuecomment-1142384255

2022-06-01 08:48 UTC, casparvl commented
Even with the download URL in ../redist/... the naming scheme of the sources (`cudnn-linux-x86_64-8.4.0.27_cuda11.6-archive.tar.xz`) is still different from it used to be (e.g. `cudnn-11.1-linux-x64-v8.0.4.30.tgz`). In particular, the `cudnnarch` used previously would be `x64`, now it needs to be `x86_64` to construct the proper filename. Thus, the update in this PR is still needed.

2022-06-01 10:37 UTC, branfosj commented
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _cuDNN-8.0.4.30-CUDA-11.0.2.eb_ 
 * **SUCCESS** _cuDNN-8.2.1.32-CUDA-11.3.1.eb_ 
 * **SUCCESS** _CUDA-10.1.243.eb_ 
 * **FAIL (build issue)** _CUDA-11.4.1.eb_ (partial log available at https://gist.github.com/1ad7982fb4e2864f24fb6e7c5f080223)
 * **SUCCESS** _cuDNN-7.6.2.24-CUDA-10.1.243.eb_ 
 * **FAIL (build issue)** _cuDNN-8.2.2.26-CUDA-11.4.1.eb_ (partial log available at https://gist.github.com/bd794465127f6ff53e1673a69ba06e12)

Build succeeded for 4 out of 6 (4 easyconfigs in total)
bear-pg0305u15a.bear.cluster - Linux RHEL 8.5, POWER, 8335-GTX (power9le), 4 x NVIDIA Tesla V100-SXM2-16GB, 470.57.02, Python 3.6.8
See https://gist.github.com/c2fc32a2938fca54c7a3128334a39347 for a full test report.

2022-06-01 10:48 UTC, branfosj commented
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _cuDNN-7.6.2.24-CUDA-10.1.243.eb_ 
 * **SUCCESS** _cuDNN-8.0.4.30-CUDA-11.0.2.eb_ 
 * **SUCCESS** _cuDNN-8.2.1.32-CUDA-11.3.1.eb_ 
 * **SUCCESS** _cuDNN-8.2.2.26-CUDA-11.4.1.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
bear-pg0305u15a.bear.cluster - Linux RHEL 8.5, POWER, 8335-GTX (power9le), 4 x NVIDIA Tesla V100-SXM2-16GB, 470.57.02, Python 3.6.8
See https://gist.github.com/f8d3fa25500a89d1a3f2df58f61013e4 for a full test report.

2022-06-01 10:54 UTC, branfosj commented
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _CUDA-10.1.243.eb_ 
 * **SUCCESS** _CUDAcore-11.0.2.eb_ 
 * **SUCCESS** _CUDA-11.3.1.eb_ 
 * **SUCCESS** _CUDA-11.4.1.eb_ 
 * **SUCCESS** _cuDNN-7.6.2.24-CUDA-10.1.243.eb_ 
 * **SUCCESS** _cuDNN-8.0.4.30-CUDA-11.0.2.eb_ 
 * **SUCCESS** _cuDNN-8.2.1.32-CUDA-11.3.1.eb_ 
 * **SUCCESS** _cuDNN-8.2.2.26-CUDA-11.4.1.eb_ 

Build succeeded for 8 out of 8 (4 easyconfigs in total)
bear-pg0103u01a.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz (icelake), 2 x NVIDIA NVIDIA A100-PCIE-40GB, 470.57.02, Python 3.6.8
See https://gist.github.com/872ae98ef7f5dc378b2cd594c036413a for a full test report.

2022-06-01 16:42 UTC, branfosj requested changes

2022-06-03 08:51 UTC, branfosj commented on easybuild/easyblocks/c/cudnn.py
> +        cudnnarch = False
```suggestion
        cudnnarch = False
```

Sorry!

2022-06-03 08:57 UTC, branfosj commented
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _cuDNN-7.6.2.24-CUDA-10.1.243.eb_ 
 * **SUCCESS** _cuDNN-8.0.4.30-CUDA-11.0.2.eb_ 
 * **SUCCESS** _cuDNN-8.2.1.32-CUDA-11.3.1.eb_ 
 * **SUCCESS** _cuDNN-8.2.2.26-CUDA-11.4.1.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
bear-pg0305u15a.bear.cluster - Linux RHEL 8.5, POWER, 8335-GTX (power9le), 4 x NVIDIA Tesla V100-SXM2-16GB, 470.57.02, Python 3.6.8
See https://gist.github.com/1bfea400d4d171059d1b828f95a3c06e for a full test report.

2022-06-03 08:59 UTC, branfosj approved these changes
lgtm

2022-06-03 09:00 UTC, branfosj commented
Test report by @branfosj
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _cuDNN-7.6.2.24-CUDA-10.1.243.eb_ 
 * **SUCCESS** _cuDNN-8.0.4.30-CUDA-11.0.2.eb_ 
 * **SUCCESS** _cuDNN-8.2.1.32-CUDA-11.3.1.eb_ 
 * **SUCCESS** _cuDNN-8.2.2.26-CUDA-11.4.1.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
bear-pg0105u36b.bear.cluster - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (icelake), Python 3.6.8
See https://gist.github.com/d840c081a097e754848f1a5c8e404ae8 for a full test report.

2022-06-03 09:01 UTC, branfosj commented
Going in, thanks @casparvl!

2022-06-03 09:01 UTC, merged

2022-06-03 09:02 UTC, casparvl commented
I was just about to remove the trailing whitespace (annoying how committing suggested changes often leads to these things...), but you were too fast ;-) Thanks @branfosj for the assist.