Changes in the shared library names with qt versions they are compiled with.
easybuilders/easybuild-easyblocks pull request #2730
Opened 2022-06-02 11:50 UTC by satishskamath

For the newer versions of libQGLviewer the qt versions are also included in the library names, therefore sanity check needs to be modified.

2022-06-09 18:24 UTC, Micket requested changes

2022-06-09 18:24 UTC, Micket commented on easybuild/easyblocks/l/libqglviewer.py
> +                    addition = '-' + addition
I think this looks a bit cryptic and seems a bit fragile considering things like `QtPy` `Qtconsole`  etc.
I'd say just go with hardcoding Qt5 and 6 for now. We'll worry about generalizing it in 10 years when Qt7 comes.
```suggestion
            for qt_dep in ['Qt5', 'Qt6']:
                if get_software_root('Qt5'):
                    addition = qt_dep.lower()
                    break
            else:
                raise EasyBuildError("Missing Qt5 or Qt6 dependency")
```

2022-06-13 00:15 UTC, Minidixit submitted a review, later dismissed

2022-06-15 18:56 UTC, Micket requested changes

2022-06-15 18:56 UTC, Micket commented on easybuild/easyblocks/l/libqglviewer.py
> +            }
Sorry for nitpicking here, but i think deduplicating it a bit like this is nicer, and `suffix` seems a bit more appropriate name
```suggestion
        if LooseVersion(self.version) < LooseVersion("2.8.0"):
            suffix = ''
        else:
            for dep in ['Qt5', 'Qt6']:
                if get_software_root(dep):
                    suffix = '-' + dep.lower()
                    break
            else:
                raise EasyBuildError("Missing Qt5 or Qt6 dependency")
        custom_paths = {
            'files': [('lib/libQGLViewer'+addition+'.prl', 'lib64/libQGLViewer'+addition+'.prl'),
                      ('lib/libQGLViewer'+addition+'.%s' % shlib_ext,
                          'lib64/libQGLViewer'+addition+'.%s' % shlib_ext)],
            'dirs': ['include/QGLViewer'],
        }
```

2022-06-15 21:42 UTC, Micket requested changes

2022-06-15 21:42 UTC, Micket commented on easybuild/easyblocks/l/libqglviewer.py
> +            suffix = ''
```suggestion
```

2022-06-15 21:42 UTC, Micket commented on easybuild/easyblocks/l/libqglviewer.py
> +                    suffix = '-' + suffix
```suggestion
                    suffix = '-' + dep.lower()
```

2022-08-01 14:16 UTC, Micket approved these changes
lgtm

2022-08-01 17:06 UTC, Micket commented
I need a test report before i can merge this. Do you have a PR for a newer libQGLViewer?

2022-08-01 21:21 UTC, satishskamath commented
> I need a test report before i can merge this. Do you have a PR for a newer libQGLViewer?
https://github.com/easybuilders/easybuild-easyconfigs/pull/15945 , I just created a PR for the easyconfig. But the tests will fail without this PR. :)

2022-08-02 13:01 UTC, merged