use det_cmake_version function to determine CMake version in CMakeMake generic easyblock
easybuilders/easybuild-easyblocks pull request #2772
Opened 2022-08-06 09:24 UTC by boegel

Follow-up for #2514, which takes into account that:

* CMake may not be loaded as a (build) dependency, which results in a hard crash without these changes because `None` is fed to `LooseVersion` (cfr. https://github.com/easybuilders/easybuild-easyblocks/pull/2514#discussion_r937960734)
* CMake may be filtered out as a dependency, because `cmake` in OS is preferred instead

`det_cmake_version` produces a clean error message if the CMake version could not be determined (for example if the `cmake` command is not found)

2022-08-09 15:57 UTC, casparvl commented
Test report by @casparvl
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _snappy-1.1.8-GCCcore-10.3.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1 - Linux RHEL 8.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/d9c48b9db80f34a58ee9699f9e8c1f50 for a full test report.

2022-08-09 15:58 UTC, casparvl commented
Test report by @casparvl
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _snappy-1.1.8-GCCcore-10.3.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
tcn1 - Linux RHEL 8.4, x86_64, AMD EPYC 7H12 64-Core Processor, Python 3.6.8
See https://gist.github.com/bc0abe1305f52d68c80671e92d8e26a7 for a full test report.

2022-08-09 16:00 UTC, Flamefire requested changes

2022-08-09 16:02 UTC, casparvl approved these changes
Looks good to me.

I've tested with snappy (which uses `CMakeMake`) with and without ` --filter-deps=CMake`. Both builds completed successfully, and both builds did not set things like `CMAKE_CXX_FLAGS`, indicating that they took the correct code path when evaluating:

```
if LooseVersion(cmake_version) < LooseVersion('2.8.0') or cache_exists:
``` 

I see @Flamefire is more critical on the tests though. So, I'll leave this open. @Flamefire once you're happy too, feel free to hit merge :)

2022-09-09 17:44 UTC, boegel commented on easybuild/easyblocks/generic/cmakemake.py
> +        regex = re.compile(r"^cmake version (?P<version>[0-9]\.[0-9a-zA-Z.-]+)$", re.M)
fixed in 6876e7acbef712270ec16ca9c39d5f3996f0d9cc

2022-09-09 17:44 UTC, boegel commented on test/easyblocks/easyblock_specific.py
> +        echo "cmake version 7.8.9"
fixed in 6876e7acbef712270ec16ca9c39d5f3996f0d9cc

2022-09-09 17:44 UTC, boegel commented on test/easyblocks/easyblock_specific.py
> +        # output of 'cmake --version' as produced by CMake 2.x
fixed in 6876e7acbef712270ec16ca9c39d5f3996f0d9cc

2022-09-09 18:25 UTC, boegel commented
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Z3-4.8.16-GCCcore-11.3.0.eb_ 
 * **SUCCESS** _pybind11-2.6.2-GCCcore-10.3.0.eb_ 
 * **SUCCESS** _kallisto-0.48.0-gompi-2021b.eb_ 
 * **SUCCESS** _netCDF-4.8.1-iimpi-2021b.eb_ 

Build succeeded for 4 out of 4 (4 easyconfigs in total)
node3114.skitty.os - Linux RHEL 8.4, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/e45bf82c602358979b0f4f73b84e8d8a for a full test report.

2022-09-10 00:07 UTC, bartoldeman approved these changes
Lgtm this one had sufficient eyes on it and looks good to me too

2022-09-10 00:07 UTC, merged