add easyblock for JuliaBundle
easybuilders/easybuild-easyblocks pull request #2830
Opened 2022-11-16 16:04 UTC by lexming

2022-11-16 16:14 UTC, boegel requested changes

2022-11-17 01:52 UTC, lexming commented on easybuild/easyblocks/generic/juliabundle.py
> +        self.cfg.enable_templating = prev_enable_templating
indeed, using `with` is way better, thanks! :+1:
fixed in https://github.com/easybuilders/easybuild-easyblocks/pull/2830/commits/118e33bc2971731d6948ce7d5f4ffbb25e3f1917

2022-11-17 01:53 UTC, lexming commented on easybuild/easyblocks/generic/juliabundle.py
> +        super(JuliaBundle, self).sanity_check_step(*args, **kwargs)
I thought it was weird that `PythonBundle` is not using `custom_paths`, but I had no idea about the reason behind it. Fixed in https://github.com/easybuilders/easybuild-easyblocks/pull/2830/commits/bde9df58e4798440f6aa96bee571a4c38357690e

2022-11-17 01:54 UTC, lexming commented
Updated with default definition of sources to avoid filename collisions.

2022-11-24 11:14 UTC, boegel requested changes

2022-11-24 12:59 UTC, lexming commented on easybuild/easyblocks/generic/juliabundle.py
> +    Bundle of modules: only generate module files, nothing to build/install
fixed in https://github.com/easybuilders/easybuild-easyblocks/pull/2830/commits/47314783a57dd0168f901688b2ca066bb2bc6968 :+1:

2022-11-24 13:41 UTC, boegel approved these changes

2022-11-24 13:41 UTC, merged