void pytorch test_step crashing if runtest is not a command
easybuilders/easybuild-easyblocks pull request #2883
Opened 2023-02-09 07:47 UTC by akesandgren

(created using `eb --new-pr`)

2023-02-09 08:13 UTC, Flamefire commented
The changeset is huge and it is not exactly clear what is going on here. What is the use case? Why/when would `run_test` be not a string?

How about changinging `tests_out, tests_ec = super(EB_PyTorch, self).test_step(return_output_ec=True)` to:
```
test_result = super(EB_PyTorch, self).test_step(return_output_ec=True)
if test_result is None:
    # Test skipped
    return
tests_out, tests_ec = test_result
```

And maybe log a message instead of the "Test skipped" comment.
This keeps all the handling IF a test should be run to the super-test_step and only handles the case where it isn't run

But again: Why would you want that given that we have `--ignore-test-failure` and `--skip-test-step`?

2023-02-09 08:16 UTC, akesandgren commented
Because someone might get into their heads (like me) to set runtest = False which would then result in a crash...
So it's mostly about making sure that bad things don't happen unexpectedly.

2023-02-09 08:20 UTC, Flamefire commented
> Because someone might get into their heads (like me) to set runtest = False which would then result in a crash... So it's mostly about making sure that bad things don't happen unexpectedly.

Then maybe add to the very top of the function a `if self.cfg['runtest'] is False` to make this explicit but IMO the proposed solution is better. Or a clear error when it is not a string_type.

But I'd really use an early return here. Avoids all that indentation and complications

2023-02-09 08:28 UTC, akesandgren commented
Well runtest = True also crashes, but the
test_result = super(EB_PyTorch, self).test_step(return_output_ec=True)
version is probably easier to get right.

2023-02-09 08:35 UTC, Flamefire commented
> Well runtest = True also crashes,

True (no pun intended). Then maybe instead of logging "Tests skipped" we should simply throw an `EasyBuildError` if the result is `None` maybe with some handling of the potential values. E.g. `runtest=False` -> Refer to `--skip-test-step`, `runtest` set (`if runtest:`) -> Likely invalid format, otherwise unknown error in the super-method

2023-02-09 09:59 UTC, akesandgren commented
Wouldn't it be better to pick up on this as early as possible... i.e. at init time or so...

2023-02-09 11:24 UTC, Flamefire commented
> Wouldn't it be better to pick up on this as early as possible... i.e. at init time or so...

Not sure if we really want to duplicate the logic. E.g. the super-test_step does some checking e.g. against `self.testcmd` and only then decides whether to run the tests. And all official ECs have this right anyway. So I'd just improve the error, not preventatively avoid it.   
My thinking is that if we change e.g. the conditions in (super-)test_step or set `self.testcmd` somewhere in pytorch we could miss that error handling in `__init__` which could become plain wrong. Hence I like the Python mantra: "Better ask for forgiveness than permission" --> Handle the error case if and when it appears. Not avoid it in case someone broke something.

2023-02-09 11:33 UTC, akesandgren commented
Ok, makes sense. just tired of waiting for +30min of building before the code hits the problem :-)

2023-02-09 12:19 UTC, akesandgren commented
@Flamefire something like this?

2023-02-09 13:21 UTC, Flamefire requested changes
Yes almost. I'd invert the condition though such that the "False" message is correct and the other a best guess.

2023-02-09 13:21 UTC, Flamefire commented on easybuild/easyblocks/p/pytorch.py
> +                msg = "Do not set runtest to False, use --skip-test-step instead."
```suggestion
            if self.cfg['runtest'] is False:
                msg = "Do not set runtest to False, use --skip-test-step instead."
            else:
                msg = "Tests did not run. Make sure `runtest` is set to a command."
```

2023-02-09 14:36 UTC, akesandgren commented on easybuild/easyblocks/p/pytorch.py
> +                msg = "Do not set runtest to False, use --skip-test-step instead."
changed it around now.

2023-02-09 14:46 UTC, Flamefire approved these changes

2023-03-02 15:28 UTC, boegel approved these changes
lgtm

2023-03-03 03:42 UTC, boegel commented
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _PyTorch-1.12.1-foss-2022a.eb_ (partial log available at https://gist.github.com/9121f45c935850102c496e262d160d51)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
node3118.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/bddfff9d5a0629e1915c2ed89e583698 for a full test report.

2023-03-03 09:36 UTC, boegel commented
The fact that some PyTorch tests (still) fail is irrelevant to the changes in this PR, so I'll go ahead and merge this...

2023-03-03 09:36 UTC, merged