Create non-versioned symlink for python-config
easybuilders/easybuild-easyblocks pull request #2904
Opened 2023-03-14 07:35 UTC by VRehnberg

Occasionally there are configure scripts that assume existance of python-config. But existing easybuild installations for Python3 will only create python3-config. This is a remedy to that problem. Previously discussed here:
https://easybuild.slack.com/archives/C34UA1HT7/p1678728109206609?thread_ts=1678722749.081689&cid=C34UA1HT7

2023-03-14 07:59 UTC, boegel requested changes
Let's also add `python-config --help` as sanity check command (so people can easily see that their Python installation is missing the symlink)?

Maybe also add both `bin/python` and `bin/python-config` in `files` in `sanity_check_paths` (via `custom_paths` in `sanity_check_step`) while you're at it...

2023-03-14 10:15 UTC, VRehnberg commented
> Let's also add `python-config --help` as sanity check command (so people can easily see that their Python installation is missing the symlink)?
> 
> Maybe also add both `bin/python` and `bin/python-config` in `files` in `sanity_check_paths` (via `custom_paths` in `sanity_check_step`) while you're at it...

I added versioned python-config in sanity check as well to make it consistent with sanity checks for python. Let me know if you think it's unnecessary and I'll remove it.

2023-03-14 14:39 UTC, boegel requested changes

2023-03-14 14:39 UTC, boegel commented on easybuild/easyblocks/p/python.py
> +            "python-config --help",  # make sure that symlink was created correctly
@VRehnberg Maybe move this up, right below the `python --version` check?

2023-03-15 17:19 UTC, boegel approved these changes
lgtm

2023-03-15 19:55 UTC, boegel commented
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Python-2.7.16-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _Python-2.7.18-GCCcore-11.2.0-bare.eb_ 
 * **SUCCESS** _Python-3.7.4-GCCcore-8.3.0.eb_ 
 * **SUCCESS** _Python-3.9.6-GCCcore-11.2.0.eb_ 
 * **SUCCESS** _Python-3.10.8-GCCcore-12.2.0.eb_ 

Build succeeded for 5 out of 5 (5 easyconfigs in total)
node3170.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/8a3963c2d9d64df3ab0fa83b2b6aa9b2 for a full test report.

2023-03-15 21:02 UTC, merged