add `PerlBundle` generic easyblock for installing a bundle of Perl modules
easybuilders/easybuild-easyblocks pull request #2945
Opened 2023-06-05 09:38 UTC by Micket

(created using `eb --new-pr`)

2023-06-21 07:36 UTC, boegel requested changes

2023-06-21 07:36 UTC, boegel commented on easybuild/easyblocks/generic/perlbundle.py
> +# Copyright 2018-2021 Ghent University
```suggestion
# Copyright 2018-2023 Ghent University

2023-06-21 07:37 UTC, boegel approved these changes

2023-06-21 11:10 UTC, Micket commented on easybuild/easyblocks/generic/perlbundle.py
> +        self.cfg['exts_filter'] = ("perl -e 'require %(ext_name)s'", '')
If the perl easyblock uses this as well we could import the variable. I thought it more important to do the right thing from the start here.

2023-06-21 11:20 UTC, boegel commented
tested with https://github.com/easybuilders/easybuild-easyconfigs/pull/17970, ready to go, thanks @Micket!

2023-06-21 11:20 UTC, merged

2023-09-25 10:51 UTC, Flamefire commented
This causes trouble on Python2 due to the umlaut --> https://github.com/easybuilders/easybuild-easyblocks/pull/3008