enhance PythonPackage easyblock to deal with `posix_local` installation scheme used by Python in recent Debian/Ubuntu versions
easybuilders/easybuild-easyblocks pull request #2977
Opened 2023-08-04 20:52 UTC by boegel

fixes #2976

2023-08-04 20:58 UTC, boegel commented
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _EasyBuild-4.8.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4012.donphan.os - Linux Ubuntu 22.04.1 LTS (Jammy Jellyfish), x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 3.10.6
See https://gist.github.com/boegel/0bbe4047ad6d144046c282740c93d802 for a full test report.

2023-08-04 20:59 UTC, boegel commented
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _EasyBuild-4.8.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
vpnz200.ugent.be - Darwin UNKNOWN UNKNOWN, AArch64, Apple M1 (m1), Python 3.9.6
See https://gist.github.com/boegel/7dfc46cfb795d3e1d5ed413711b8f0ea for a full test report.

2023-08-04 21:06 UTC, boegel commented
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _EasyBuild-4.8.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node3106.skitty.os - Linux RHEL 8.6, x86_64, Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (skylake_avx512), Python 3.6.8
See https://gist.github.com/boegel/a668b898634f0bbf5da4e0a032d86721 for a full test report.

2023-08-04 21:23 UTC, boegel commented
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Python-3.11.3-GCCcore-12.3.0.eb_ 

Build succeeded for 1 out of 1 (1 easyconfigs in total)
node4012.donphan.os - Linux Ubuntu 22.04.1 LTS (Jammy Jellyfish), x86_64, Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (cascadelake), Python 3.10.6
See https://gist.github.com/boegel/a2fa138d863eb40989cb6e4cd4962cc5 for a full test report.

2023-08-24 10:19 UTC, jfgrimm requested changes

2023-08-24 10:19 UTC, jfgrimm commented on easybuild/easyblocks/generic/pythonpackage.py
> +        # symlink subdirectories of <prefix>/local to directly into <prefix>
```suggestion
        # symlink subdirectories of <prefix>/local directly into <prefix>
```

2023-08-24 10:19 UTC, jfgrimm commented on easybuild/easyblocks/generic/pythonpackage.py
> +        * symlinking site-packages to dist-packages is only the former is available;
```suggestion
        * symlinking site-packages to dist-packages if only the former is available;
```

2023-08-24 12:39 UTC, jfgrimm approved these changes
lgtm

2023-08-24 12:43 UTC, jfgrimm commented
Going in, thanks @boegel!

2023-08-24 12:43 UTC, merged