New easyblock for building QuantumESPRESSO with CMake
easybuilders/easybuild-easyblocks pull request #3257
Opened 2024-03-18 14:54 UTC by Crivella

Since Quantum Espresso 7.x,  the configure/make build has been less supported in favor of CMake/Make.

Right now bot methods of building QE coexist, but some features, like the installation of the `pw2qmcpack` are only supported in the CMake version.

Further more, the CMake implementation should be able to much more easily recognize the present external libraries and pickup environment variables set by easy build, and also properly implement parallelization in Make, allowing to build and test QE much faster (the old Config/Make would need `make` to be run multiple times to reach the end if ran with more than 1 parallel process)

2024-03-18 14:57 UTC, Crivella commented on easybuild/easyblocks/q/quantumespressocmake.py
> +        if self.cfg.get('build_shared_libs', False) :
Fixed in f4b87a69

2024-03-18 14:57 UTC, Crivella commented on easybuild/easyblocks/q/quantumespressocmake.py
> +        # Example output for reported failures:
Fixed in f4b87a69

2024-03-18 15:17 UTC, Crivella commented
One thing to note is that compilation of some QE components and plugins has been moved to an implementantion with `submodule` pulling data from a specific commit
Offline building is still possible but will require more careful implementation, at least if we still want to check the hash, while running the script as suggested [on the QE wiki](https://gitlab.com/QEF/q-e/-/wikis/Support/Build-without-internet).

While it is possible to emulate what the script is doing, i would prefer to keep it as a source of truth, in case paths/implementation are changed in future versions.

2024-04-05 13:25 UTC, ocaisa requested changes

2024-04-05 13:25 UTC, ocaisa commented on easybuild/easyblocks/q/quantumespresso.py
> +        if LooseVersion(self.version) < LooseVersion("7.3.1"):
```suggestion
        if LooseVersion(self.version) >= LooseVersion("7.3.1"):
```

2024-04-05 13:35 UTC, ocaisa approved these changes
LGTM

2024-04-05 13:37 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3
EB_ARGS="QuantumESPRESSO-7.3-foss-2023a.eb"

2024-04-05 16:42 UTC, Crivella commented
This flakiness with the thresholds on the test-suite...

2024-04-05 16:57 UTC, ocaisa commented
There is a PR open that addresses the single failing test issue that we have seen for QE in EESSI for the original easyblock. The reason for running that build here was just a sanity check, and that was ok.

In https://github.com/easybuilders/easybuild-easyconfigs/pull/20138 we have the checks for the new easyblock.

2024-04-05 16:57 UTC, merged

2024-04-05 16:59 UTC, ocaisa commented
@boegelbot please test @ jsc-zen3

2024-04-05 19:10 UTC, ocaisa commented on easybuild/easyblocks/q/quantumespressocmake.py
> +class EB_QuantumESPRESSOcmake(CMakeMake):
I had a different plan, I was going to do a follow-up PR when the open QE easyconfigs are merged, where we use an explicit easyblock for the configuremake-based easyconfigs and then switch this to the standard

2024-04-05 19:11 UTC, ocaisa commented on easybuild/easyblocks/q/quantumespressocmake.py
> +class EB_QuantumESPRESSOcmake(CMakeMake):
It would be a lot of (pointless?) effort to merge them