use `run_shell_cmd` in custom easyblock for Mathematica
easybuilders/easybuild-easyblocks pull request #3298
Opened 2024-04-07 08:19 UTC by branfosj

(created using `eb --new-pr`)

2024-04-08 10:56 UTC, Micket commented on easybuild/easyblocks/m/mathematica.py
> +# Copyright 2013-2023 Ghent University
```suggestion
# Copyright 2013-2024 Ghent University
```

2024-04-11 08:18 UTC, boegel approved these changes
lgtm

2024-04-11 08:32 UTC, boegel requested changes

2024-04-11 08:32 UTC, boegel commented on easybuild/easyblocks/m/mathematica.py
> +                (r"or press ENTER to select /usr/local/bin: >", os.path.join(self.installdir, "bin")),
There are a couple of line breaks in this question, so we need to use `[\s\n]*`:
```suggestion
               (r"or press ENTER to select[\s\n]*/usr/local/.*:[\s\n]*>", os.path.join(self.installdir, "bin")),
```

2024-04-11 08:34 UTC, boegel requested changes

2024-04-11 08:34 UTC, boegel commented on easybuild/easyblocks/m/mathematica.py
> +               (r"or press ENTER to select[\s\n]*/usr/local/.*:[\s\n]*>", os.path.join(self.installdir, "bin")),
```suggestion
                (r"or press ENTER to select[\s\n]*/usr/local/.*:[\s\n]*>", os.path.join(self.installdir, "bin")),

2024-04-11 08:41 UTC, boegel approved these changes

2024-04-11 09:00 UTC, boegel requested changes

2024-04-11 09:00 UTC, boegel commented on easybuild/easyblocks/m/mathematica.py
> +                (r"Create directory \(y/n\)\? >", 'y'),
```suggestion
                (r"Create directory \(y/n\)\?[\s\n]*>", 'y'),
```

2024-04-11 09:00 UTC, boegel commented on easybuild/easyblocks/m/mathematica.py
> +                (r"Should the installer attempt to make this change \(y/n\)\? >", 'n'),
```suggestion
                (r"Should the installer attempt to make this change \(y/n\)\?[\s\n]*>", 'n'),
```

2024-04-11 09:00 UTC, boegel commented on easybuild/easyblocks/m/mathematica.py
> +                (r"Enter the installation directory, or press ENTER to select %s: >" % qa_install_path,
```suggestion
                (r"Enter the installation directory, or press ENTER to select %s:[\s\n]*>" % qa_install_path,
```

2024-04-11 09:38 UTC, boegel requested changes

2024-04-11 09:38 UTC, boegel commented on easybuild/easyblocks/m/mathematica.py
> +                (r"or press ENTER to select[\s\n]*/usr/local/.*:[\s\n]*>", os.path.join(self.installdir, "bin")),
```suggestion
                (r"or press ENTER to select[\s\n]*/usr/local/bin:[\s\n]*>", os.path.join(self.installdir, "bin")),
```

2024-04-11 09:41 UTC, boegel requested changes
fix question pattern to specify installation prefix in Mathematica easyblock

2024-04-11 09:41 UTC, boegel commented on easybuild/easyblocks/m/mathematica.py
> +                (r"Enter the installation directory, or press ENTER to select %s:[\s\n]*>" % qa_install_path,
```suggestion
                (r"Enter the installation directory, or press ENTER to select[\s\n]*%s:[\s\n]*>" % qa_install_path,

2024-04-11 10:03 UTC, boegel commented
Test report by @boegel
#### Overview of tested easyconfigs (in order)
 * **SUCCESS** _Mathematica-12.1.1.eb_ 
 * **SUCCESS** _Mathematica-13.1.0.eb_ 

Build succeeded for 2 out of 2 (2 easyconfigs in total)
node3564.doduo.os - Linux RHEL 8.8, x86_64, AMD EPYC 7552 48-Core Processor, Python 3.6.8
See https://gist.github.com/boegel/91aa51c042a01ff063e2f9b3291f207a for a full test report.

2024-04-11 10:04 UTC, merged