new easyblock for blis
easybuilders/easybuild-easyblocks pull request #3385
Opened 2024-07-08 03:28 UTC by wwweert123

(created using `eb --new-pr`)

2024-07-08 08:19 UTC, wwweert123 commented
https://github.com/EESSI/software-layer/blob/f64a20d373a3047a55315a92401c0610bf526844/eb_hooks.py#L343-L358 This easyblock for BLIS was implemented to also take into account building on A64FX cpu architecture where additional configure opts are needed.

2024-07-31 13:56 UTC, boegel requested changes
Thanks a lot for the contribution @wwweert123!

Do you mind also opening a companion PR for the recent BLIS easyconfigs, so clean them up so the custom easyblock for BLIS is being used?

Of course we'll make sure that this PR gets merged first...

2024-07-31 13:56 UTC, boegel commented on easybuild/easyblocks/b/blis.py
> +            'shared_enable': [True, "Enable builing shared library", CUSTOM],
I think `enable_cblas` makes more sense? Also we like to keep these sorted alphabetically:

```suggestion
            'enable_cblas': [True, "Enable CBLAS", CUSTOM],
            'enable_shared': [True, "Enable builing shared library", CUSTOM],
            'multi_threading_type': ["openmp", "Type of multithreading to use", CUSTOM],
```

2024-07-31 14:02 UTC, wwweert123 commented
> Thanks a lot for the contribution @wwweert123!
> 
> 
> 
> Do you mind also opening a companion PR for the recent BLIS easyconfigs, so clean them up so the custom easyblock for BLIS is being used?
> 
> 
> 
> Of course we'll make sure that this PR gets merged first...

Oh yes, I have created a companion PR BLIS easyconfig that makes use of this custom easyblock. I had forgotten to mention it here in this PR. 

https://github.com/easybuilders/easybuild-easyconfigs/pull/20973

2025-07-01 12:06 UTC, Thyre commented
This is probably not required anymore since #3773 is merged, right?

2025-07-02 14:35 UTC, boegel commented
Yeah, this has bit-rotted a bit unfortunately...

Maybe @smoors can take a look if there's anything in here that should be ported over to the custom easyblock for BLIS that got merged via #3773 (and if not, close this)

2025-09-04 12:49 UTC, Crivella commented
Beside minor differences in the behavior of the EConfing extra parameters the other relevant difference would be for `a64fx` 

```
        # arch_name will only be available when archspec is available to easybuild, else arch_name will be unknown
        arch_name = get_cpu_arch_name()
        if arch_name == "a64fx":
            self.cfg.update('configopts', 'CFLAGS="$CFLAGS -DCACHE_SECTOR_SIZE_READONLY"')
```

 which we are not passing

2025-09-10 06:55 UTC, boegel commented
> Beside minor differences in the behavior of the EConfing extra parameters the other relevant difference would be for `a64fx`
> 
> ```
>         # arch_name will only be available when archspec is available to easybuild, else arch_name will be unknown
>         arch_name = get_cpu_arch_name()
>         if arch_name == "a64fx":
>             self.cfg.update('configopts', 'CFLAGS="$CFLAGS -DCACHE_SECTOR_SIZE_READONLY"')
> ```
> 
> which we are not passing

That would definitely be helpful to have, since in EESSI we now deal with this in a hook: 
- https://github.com/EESSI/software-layer-scripts/pull/75

2025-09-10 10:02 UTC, boegel commented
@smoors Can you take a look at a follow-up PR for the BLIS easyblock that applies the additional things that were done in this PR but not in your merged PR https://github.com/easybuilders/easybuild-easyblocks/pull/3773 ?

2025-09-20 19:58 UTC, smoors commented
> @smoors Can you take a look at a follow-up PR for the BLIS easyblock that applies the additional things that were done in this PR but not in your merged PR #3773 ?

done in https://github.com/easybuilders/easybuild-easyblocks/pull/3938

2025-09-20 19:58 UTC, closed without merging