inclding subdirectory of include for SuiteSparse
easybuilders/easybuild-easyblocks pull request #3391
Opened 2024-07-10 15:44 UTC by tanmoy1989

(created using `eb --new-pr`)

2024-07-16 15:48 UTC, zao commented
Test report by @zao
#### Overview of tested easyconfigs (in order)
 * **FAIL (build issue)** _PETSc-3.19.2-foss-2022b.eb_ (partial log available at https://gist.github.com/zao/b035ccb550e7c11195a42bb78e706a87)

Build succeeded for 0 out of 1 (1 easyconfigs in total)
eb-mix.zao.se - Linux Rocky Linux 9.4 (Blue Onyx), x86_64, AMD Ryzen 9 3900X 12-Core Processor (zen2), Python 3.9.18
See https://gist.github.com/zao/4fa75f6450d7a51a0a2a1c51522b2df3 for a full test report.

2024-07-16 15:51 UTC, zao commented
It seems like the PETSc build gets angry if any of the SuiteSparse include directory candidates given on the command line doesn't exist, see the test report in https://github.com/easybuilders/easybuild-easyblocks/pull/3391#issuecomment-2231276382 above.

This logic probably needs to guard the additional entry behind whether the directory actually exists on the filesystem.

2024-07-17 14:56 UTC, tanmoy1989 commented
Thanks @zao: I would really appreciate if you could provide suggestions on how to proceed further. I am running out of options and a bit confused too.

2024-07-18 15:33 UTC, ocaisa commented on easybuild/easyblocks/p/petsc.py
> +                    inc_spec = "-include=[%s]" % ','.join(suitesparse_incs)
```suggestion
                    suitesparse_incs = [suitesparse_inc]
                    # SuiteSparse can install its headers into a subdirectory of the include directory instead.
                    suitesparse_inc_subdir = os.path.join(suitesparse_inc, 'suitesparse')
                    if os.path.exists(suitesparse_inc_subdir):
                      suitesparse_incs.append(suitesparse_inc_subdir)
                    inc_spec = "-include=[%s]" % ','.join(suitesparse_incs)
```
Maybe something like this?

2024-07-31 14:19 UTC, boegel commented
@tanmoy1989 While I'm not opposing the proposed change, as long as it doesn't cause trouble with builds that were working fine before, I do wonder what's triggering the different subdirectory to be used instead?

2024-08-02 09:29 UTC, tanmoy1989 commented
@boegel: I am not sure if I understood your question completely, however, I am fully Ok if you suggest any changes to be made before merging the PR.

2024-08-13 21:19 UTC, boegel commented
@tanmoy1989 I guess my question is what triggered you to look into implemented these changes.

I'm not sure how come we did run into this before, but maybe I'm missing something...

2024-08-14 20:34 UTC, tanmoy1989 commented
Well, the main triggering point was the stage where `PETSc` was failing to build. Then @zao suggested some changes ([here](https://github.com/easybuilders/easybuild-easyconfigs/pull/20568) and over EasyBuild slack) and I followed that which ultimately brings down to this custom easyblock. The `.eb` file for `PETSc` can be found [here](https://github.com/easybuilders/easybuild-easyconfigs/pull/20568) where a detailed discussion with @zao took place.

2024-08-28 14:48 UTC, boegel commented
@tanmoy1989 Thanks for clarifying, I'll see if I can get this merged ASAP to be included in the upcoming EasyBuild v4.9.3...

There's a small code style issue to fix:
```
./easybuild/easyblocks/p/petsc.py:269:23: E111 indentation is not a multiple of 4
```

We can deal with this ourselves though if that's easier for you

2024-08-28 15:02 UTC, tanmoy1989 commented
@boegel Many thanks! I would really appreciate if the indentation part could be kindly taken care of.

2024-08-28 18:35 UTC, boegel requested changes

2024-08-28 18:35 UTC, boegel commented on easybuild/easyblocks/p/petsc.py
> +                      suitesparse_incs.append(suitesparse_inc_subdir)
```suggestion
                        suitesparse_incs.append(suitesparse_inc_subdir)

2024-08-28 20:07 UTC, boegel approved these changes
lgtm

2024-09-04 14:29 UTC, boegel commented
@boegelbot please test @ generoso
EB_ARGS="PETSc-3.19.2-foss-2022b.eb PETSc-3.20.3-foss-2023a.eb --installpath /tmp/$USER/pr3391"

2024-09-04 16:43 UTC, merged