remove use of deprecated parse_log_for_error in rpackage
easybuilders/easybuild-easyblocks pull request #3515
Opened 2024-11-23 16:35 UTC by branfosj

(created using `eb --new-pr`)

2024-12-03 20:30 UTC, boegel requested changes

2024-12-20 13:11 UTC, branfosj commented on easybuild/easyblocks/generic/rpackage.py
> +            r = reg.search(line)
done in 9bb5841

2024-12-20 13:24 UTC, branfosj commented
There are test reports using this in https://github.com/easybuilders/easybuild-easyconfigs/pull/21908

2024-12-21 11:45 UTC, lexming approved these changes
LGTM

2024-12-21 11:46 UTC, lexming commented
Merging, thanks @branfosj

2024-12-21 11:47 UTC, lexming approved these changes

2024-12-21 11:48 UTC, merged